AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Speech AI Workshop for Utilities. SAM Template for shared resources that have no specific service as their owner.

# --------------------------------------------------------------------------------------------------
# Parameters.
# --------------------------------------------------------------------------------------------------

Parameters:

  # Standard parameters that should go into every service.

  Stage:
    Description: "Environment stage (dev, test, ..., prod)"
    Type: "String"
  Workload:
    Description: "Short name of the overall workload this service belongs to"
    Type: "String"
  Context:
    Description: "Short name of the context for this service (e.g. backoffice services versus business services)"
    Type: "String"
  Service:
    Description: "Short name of this service"
    Type: "String"
  WorkloadLongName:
    Description: "Long name of the overall workload this service belongs to"
    Type: "String"
  ContextLongName:
    Description: "Long name of the context for this service (e.g. backoffice services versus business services)"
    Type: "String"
  ServiceLongName:
    Description: "Long name of this service"
    Type: "String"
  LogLevel:
    Description: "Log level for Lambda functions"
    Type: "String"
    Default: "DEBUG"
  LogRetentionInDays:
    Description: "CloudWatch Logs retention period"
    Type: "Number"
    Default: 7

  ContactCenterDataBucketName:
    Description: "Name suffix (w/o prefixes for acct ID, region, stage, workload) for contact center data bucket"
    Type: "String"
    # Reducing the long name suffix to an abbreviation, otherwise we will likely exceed the max length of 63 chars.
    Default: "cc-data"

  DataLakeDataBucketName:
    Description: "Name suffix (w/o prefixes for acct ID, region, stage, workload) for the data lake data bucket"
    Type: "String"
    # Reducing the long name suffix to an abbreviation, otherwise we will likely exceed the max length of 63 chars.
    Default: "dl-data"

  AthenaBucketName:
    Description: "Name suffix (w/o prefixes for acct ID, region, stage, workload) for the Athena bucket"
    Type: "String"
    Default: "athena-bucket"

# --------------------------------------------------------------------------------------------------
# Mappings.
# --------------------------------------------------------------------------------------------------

# --------------------------------------------------------------------------------------------------
# Globals.
# --------------------------------------------------------------------------------------------------

# --------------------------------------------------------------------------------------------------
# Resources.
# --------------------------------------------------------------------------------------------------

Resources:

  # -------------------------------------------------------------------------------------------------------------------
  # Create an S3 bucket to be used as data storage for Amazon Connect.
  # -------------------------------------------------------------------------------------------------------------------

  ContactCenterDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-${Stage}-${Workload}-${ContactCenterDataBucketName}"
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: True

  SSMParameter4ContactCenterDataBucketName:
    DependsOn: "ContactCenterDataBucket"
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Name: !Sub "/${Stage}/${Workload}/s3/${ContactCenterDataBucketName}/name"
      Description: "Name of the shared ContactCenterDataBucket"
      Value: !Ref "ContactCenterDataBucket"

  SSMParameter4ContactCenterDataBucketArn:
    DependsOn: "ContactCenterDataBucket"
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Name: !Sub "/${Stage}/${Workload}/s3/${ContactCenterDataBucketName}/arn"
      Description: "ARN of the shared ContactCenterDataBucket"
      Value: !GetAtt "ContactCenterDataBucket.Arn"

  # -------------------------------------------------------------------------------------------------------------------
  # Create an S3 bucket to be used as data storage for our little data lake.
  # -------------------------------------------------------------------------------------------------------------------

  DataLakeDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Delete"
    Properties: 
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-${Stage}-${Workload}-${DataLakeDataBucketName}"
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: True

  SSMParameter4DataLakeDataBucketName:
    DependsOn: "DataLakeDataBucket"
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Name: !Sub "/${Stage}/${Workload}/s3/${DataLakeDataBucketName}/name"
      Description: "Name of the shared DataLakeDataBucket"
      Value: !Ref "DataLakeDataBucket"

  SSMParameter4DataLakeDataBucketArn:
    DependsOn: "DataLakeDataBucket"
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Name: !Sub "/${Stage}/${Workload}/s3/${DataLakeDataBucketName}/arn"
      Description: "ARN of the shared DataLakeDataBucket"
      Value: !GetAtt "DataLakeDataBucket.Arn"

  # -------------------------------------------------------------------------------------------------------------------
  # Create an S3 bucket that serves as data lake bucket for the consumable data tier.
  # -------------------------------------------------------------------------------------------------------------------

  AthenaBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Delete"
    Properties: 
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-${Stage}-${Workload}-${AthenaBucketName}"

  SSMParameter4AthenaBucketName:
    DependsOn: "AthenaBucket"
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Name: !Sub "/${Stage}/${Workload}/s3/${AthenaBucketName}/name"
      Description: "Name of the shared AthenaBucket"
      Value: !Ref "AthenaBucket"

  SSMParameter4AthenaBucketArn:
    DependsOn: "AthenaBucket"
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Name: !Sub "/${Stage}/${Workload}/s3/${AthenaBucketName}/arn"
      Description: "ARN of the shared AthenaBucket"
      Value: !GetAtt "AthenaBucket.Arn"


# ---------------------------------------------------------------------------------------------------------------------
# Outputs.
# ---------------------------------------------------------------------------------------------------------------------

Outputs:

  # Outputs for ATHENA BUCKET
  AthenaBucketName:
    Description: "Name of the shared AthenaBucket"
    Value: !Ref "AthenaBucket"
  AthenaBucketArn:
    Description: "ARN of the shared AthenaBucket"
    Value: !GetAtt "AthenaBucket.Arn"

# ---------------------------------------------------------------------------------------------------------------------
